
@authorId = 63faa303f20e32a40404658a
@bookId = 63df508aefc8eb416be3b448

//@host = localhost:8080
@host = https://mayhem-roberts-341.onrender.com
### 
GET https://{{host}}/authors
### 
GET https://{{host}}/authors/{{authorId}}
### 
POST https://{{host}}/authors HTTP/1.1
Content-Type: application/json

{
    "author": "Rick Riordan",
    "birthday": "06/05/1964",
    "country": "USA",
    "bookCount": 39
}
### 
PUT https://{{host}}/authors/{{authorId}} HTTP/1.1
Content-Type: application/json

{
    "author": "Rick R",
    "birthday": "06/05/1964",
    "country": "USA",
    "bookCount": 50
}
### 
DELETE  https://{{host}}/authors/{{authorId}}

### 
GET https://{{host}}/books
### 
GET https://{{host}}/books/{{bookId}}
### 
POST https://{{host}}/books HTTP/1.1
Content-Type: application/json

{
    "author": "Jane Austen",
    "country": "United Kingdom",
    "imageLink": "images/pride-and-prejudice.jpg",
    "language": "Eng",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "pages": 226,
    "title": "Pride and Prejudice",
    "year": 1813
}

### 
PUT https://{{host}}/books/{{authorId}} HTTP/1.1
Content-Type: application/json

{
    "author": "Jane Austen",
    "country": "United Kingdom",
    "imageLink": "images/pride-and-prejudice.jpg",
    "language": "Eng",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "pages": 300,
    "title": "Pride and Prejudice",
    "year": 1813
}
### 
DELETE  https://{{host}}/books/{{bookId}}
