// LOCALHOST 
### 
GET http://localhost:3000/contacts 

### 
GET http://localhost:3000/contacts/63c348db248373eae5a00e29 

### 
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Sarah",
    "lastName":"Roberts",
    "email":"dinnerroll@gmail.com",
    "favoriteColor":"Blue",
    "birthday":"05/26/1997"
}

### 
PUT http://localhost:3000/contacts/63d5ae1b55c01d1d5438bd03 HTTP/1.1
Content-Type: application/json

{
    "firstName":"Sarah",
    "lastName":"Roberts",
    "email":"dinnerroll@gmail.com",
    "favoriteColor":"Red",
    "birthday":"05/26/1996"
}

### 
DELETE  http://localhost:3000/contacts/63d5ae1b55c01d1d5438bd03 HTTP/1.1


// RENDER ----------------------------------------------------------------------------------------------------------------
### 
GET https://mayhem-roberts-341-project01.onrender.com/contacts 

### 
GET https://mayhem-roberts-341-project01.onrender.com/contacts/63c348db248373eae5a00e29 

### 
POST https://mayhem-roberts-341-project01.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Giddyann",
    "lastName":"Roberts",
    "email":"doctordonk@gmail.com",
    "favoriteColor":"Green",
    "birthday":"06/22/2000"
}

### 
PUT https://mayhem-roberts-341-project01.onrender.com/contacts/ HTTP/1.1
Content-Type: application/json

{
    "firstName":"Gideon",
    "lastName":"Roberts",
    "email":"doctordonk@gmail.com",
    "favoriteColor":"Red",
    "birthday":"06/22/2000"
}

### 
POST https://mayhem-roberts-341-project01.onrender.com/contacts/ HTTP/1.1